# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Movie.destroy_all
Review.destroy_all
User.destroy_all
puts "seeding..."

nightmare_before = Movie.create({title: "Nightmare Before Christmas", genre: "Fantasy", summary: "The film follows the misadventures of Jack Skellington, Halloweentown's beloved pumpkin king. When Jack accidentally stumbles on Christmastown, he plots to bring Christmas under his control by kidnapping Santa Claus and taking over. But Jack soon discovers even the best-laid plans can go seriously awry.", poster_url: "https://m.media-amazon.com/images/M/MV5BNWE4OTNiM2ItMjY4Ni00ZTViLWFiZmEtZGEyNGY2ZmNlMzIyXkEyXkFqcGdeQXVyMDU5NDcxNw@@._V1_UY1200_CR85,0,630,1200_AL_.jpg"})
jennifers_body = Movie.create({title: "Jennifer's Body", genre: "Horror Comedy", summary: "When a demon takes possession of her, high-school hottie Jennifer (Megan Fox) turns a hungry eye on guys who never stood a chance with her before.", poster_url: "https://images.moviesanywhere.com/d35e910fc6be2965849778f6f139e47b/79d1d0f9-34be-4417-bf5f-81a391eafe46.jpg"})
halloween_town = Movie.create({title: "Halloween Town", genre: "Adventure", summary: "Marnie and her kids get a big shock when they follow grandma home to Halloweentown - and find out they come from a family of witches.", poster_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSoNuPTv_cP0WROGjGX1WmiyHaFXRI2OpktK3FiMxlTAWvXP7R5"})
practical_magic = Movie.create({title: "Practical Magic", genre: "Fantasy", summary: "Sally (Sandra Bullock) and Gillian Owens (Nicole Kidman), born into a magical family, have mostly avoided witchcraft themselves. But when Gillian's vicious boyfriend, Jimmy Angelov (Goran Visnjic), dies unexpectedly, the Owens sisters give themselves a crash course in hard magic.", poster_url: "https://m.media-amazon.com/images/M/MV5BMzU4MmNkNGYtN2I1Zi00ZDEzLTlmZjItNWQ5NWI0NzcwZDQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY1200_CR89,0,630,1200_AL_.jpg"})
shaun_of_the_dead = Movie.create({title: "Shaun of the Dead", genre: "Horror Comedy", summary: "When his town is inexplicably overrun with zombies, Shaun (Simon Pegg) must rise to the occasion and protect both Liz and his mother (Penelope Wilton).", poster_url: "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/shaun-of-the-dead-2004/large_ssY4EvRvufUZooNq1buRUrW7lCX.jpg"})
corpse_bride = Movie.create({title: "Corpse Bride", genre: "Fantasy", summary: "Victor (Johnny Depp) and Victoria's (Emily Watson) families have arranged their marriage. Though they like each other, Victor is nervous about the ceremony. While he's in a forest practicing his lines for the wedding, a tree branch becomes a hand that drags him to the land of the dead.", poster_url: "https://m.media-amazon.com/images/M/MV5BMTk1MTY1NjU4MF5BMl5BanBnXkFtZTcwNjIzMTEzMw@@._V1_UY1200_CR91,0,630,1200_AL_.jpg"})
hocus_pocus = Movie.create({title: "Hocus Pocus", genre: "Children's Film", summary: "After moving to Salem, a teenager Max accidentally frees a coven of evil witches (Bette Midler, Sarah Jessica Parker, Kathy Najimy) who used to live in the house. Now, with the help of a magical cat, the kids must steal the witches' book of spells to stop them from becoming immortal.", poster_url: "https://images.fandango.com/ImageRenderer/0/0/redesign/static/img/default_poster.png/0/images/masterrepository/Fandango/100603/HocusPocus.jpg"})
the_witch = Movie.create({title: "The Witch", genre: "Horror", summary: "In 1630 New England, panic and despair envelops a farmer, his wife and their children when youngest son Samuel suddenly vanishes. The family blames Thomasin, the oldest daughter who was watching the boy at the time of his disappearance.", poster_url: "https://m.media-amazon.com/images/M/MV5BMTUyNzkwMzAxOF5BMl5BanBnXkFtZTgwMzc1OTk1NjE@._V1_UY1200_CR90,0,630,1200_AL_.jpg"})
the_conjuring = Movie.create({title: "The Conjuring", genre: "Horror", summary: "In 1970, paranormal investigators and demonologists Lorraine and Ed Warren are summoned to the home of Carolyn and Roger Perron. The Perrons have recently moved into a secluded farmhouse, where a supernatural presence has made itself known.", poster_url: "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_.jpg"})
halloween_original = Movie.create({title: "Halloween", genre: "Horror", summary: "On a cold Halloween night in 1963, six year old Michael Myers brutally murdered his 17-year-old sister, Judith. He was sentenced and locked away for 15 years. But on October 30, 1978, Michael Myers escapes Smith's Grove. He returns to his quiet hometown where he looks for his next victims.", poster_url: "https://m.media-amazon.com/images/I/61VVvaQJJvL._AC_SY679_.jpg"})
coraline = Movie.create({title: "Coraline", genre: "Animated Horror", summary: "While exploring her new home, a girl named Coraline (Dakota Fanning) discovers a secret door, behind which lies an alternate world that closely mirrors her own but, in many ways, is better. But something sinister lays behind the facade.", poster_url: "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/coraline-2009/large_c3mwwXnI3yEpkAaumwo6XuIjNn4.jpg"})
it_follows = Movie.create({title: "It Follows", genre: "Horror", summary: "After Jay learns that she is the latest recipient of a fatal curse that is passed from victim to victim, she learns Death will creep inexorably toward her as either a friend or a stranger. Jay and her friends band together to help her flee or defend herself.", poster_url: "https://m.media-amazon.com/images/M/MV5BMmU0MjBlYzYtZWY0MC00MjliLWI3ZmUtMzhlZDVjMWVmYWY4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY1200_CR90,0,630,1200_AL_.jpg"})
monster_house = Movie.create({title: "Monster House", genre: "Children's Film", summary: "No adults believe three youths' assertion that a neighboring residence is a living creature that means them harm. With Halloween approaching, the trio must find a way to destroy the structure before innocent trick-or-treaters meet ghastly ends.", poster_url: "https://m.media-amazon.com/images/M/MV5BMTIzNjE1NDg1N15BMl5BanBnXkFtZTcwOTg2NTMzMQ@@._V1_UY1200_CR88,0,630,1200_AL_.jpg"})
haunted_mansion = Movie.create({title: "Haunted Mansion", genre: "Children's Film", summary: "Workaholic real estate agent Jim Evers takes his family on a vacation. Along the way, the family stops off at a sinister mansion that Jim has been asked to sell, only to discover it's haunted by a few spirits who need some help breaking a curse.", poster_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc9tSK0ECl1GXqdvFzkIDMl1jQ9S7CtGyXekVX6JhsVnahY7zT"})
hush = Movie.create({title: "Hush", genre: "Horror", summary: "A deaf writer who retreated into the woods to live a solitary life must fight for her life in silence when a masked killer appears in her window.", poster_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSCmZN7HixKVmwhJb6j93hnDCYTy0MmfrZwi0JhsCELTT6V9qqe"})
frankenweenie = Movie.create({title: "Frankenweenie", genre: "Children's Film", summary: "Young Victor Frankenstein is a science nerd and outsider at school, but he does have one good friend: his dog, Sparky. But then, tragedy strikes, and Sparky shuffles off this mortal coil. Victor is heartbroken, but his science teacher gives him an idea of how to jolt old Sparky back to life.", poster_url: "https://m.media-amazon.com/images/M/MV5BMjIxODY3MjEwNV5BMl5BanBnXkFtZTcwOTMzNjc4Nw@@._V1_UY1200_CR89,0,630,1200_AL_.jpg"})
casper = Movie.create({title: "Casper", genre:"Children's Film", summary: "Casper is a kind young ghost who peacefully haunts a mansion in Maine. When specialist James Harvey arrives to communicate with Casper and his fellow spirits, he brings along his teenage daughter, Kat.", poster_url: "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/casper-1995/large_1pykWukKgh0st8McAkSrtcmIFvj.jpg"})
addams_family = Movie.create({title: "The Addams Family", genre: "Comedy", summary: "When a man claiming to be Fester, the missing brother of Gomez Addams, arrives at the Addams' home, the family is thrilled. However, Morticia begins to suspect the man is a fraud, since he cannot recall details of Fester's life.", poster_url: "https://m.media-amazon.com/images/M/MV5BMzYxZTUzODYtYjQwYi00NGYzLTkxZjEtNjYwZWZlYmM0ZDg3XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg"})
scary_movie = Movie.create({title: "Scary Movie", genre: "Horror Comedy", summary: "This film boldly fires barbs at the classic scenes from Scream, The Sixth Sense, The Matrix, I Know What You Did Last Summer and The Blair Witch Project, then goes on to mock a whole myriad of teen movie clichés, no matter the genre.", poster_url: "https://prod.miramax.digital/media/assets/791_ScaryMovie_Catalog_Poster_Approved_v2.png"})
zombieland = Movie.create({title: "Zombieland", genre: "Horror Comedy", summary: "After a virus turns most people into zombies, the world's surviving humans remain locked in an ongoing battle against the hungry undead. Four of these survivors make their way to Los Angeles.", poster_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcStzQ-tKRUX5XtmbY1vy-7B5-r7OkvK6Usql_FdXx4Fot3CT5Bh"})

review1 = Review.create({movie_id: 1, user_id: 1, favorite: true, content: "Great movie! Kids might get a little nervous but still a lot of fun to watch.", scare_rating: 2})
review2 = Review.create({movie_id: 2, user_id: 1, favorite: false, content: "Pretty gory but a has some pretty good writing. Also pretty funny.", scare_rating: 4})
review3 = Review.create({movie_id: 3, user_id: 1, favorite: false, content: "Great halloween film for kids!", scare_rating: 1})
review4 = Review.create({movie_id: 4, user_id: 1, favorite: true, content: "A romantic, witchy vibe.", scare_rating: 1})
review5 = Review.create({movie_id: 5, user_id: 1, favorite: true, content: "Hilarious zombie film.", scare_rating: 3})
review6 = Review.create({movie_id: 6, user_id: 1, favorite: true, content: "A phenomenal story. Should be family friendly.", scare_rating: 2})
review7 = Review.create({movie_id: 7, user_id: 1, favorite: true, content: "A Halloween classic.", scare_rating: 1})
review8 = Review.create({movie_id: 8, user_id: 1, favorite: false, content: "Wildly unsettling.", scare_rating: 5})
review9 = Review.create({movie_id: 9, user_id: 1, favorite: true, content: "Truly terrifying.", scare_rating: 5})
review10 = Review.create({movie_id: 10, user_id: 1, favorite: false, content: "Classic horror.", scare_rating: 5})
review11 = Review.create({movie_id: 11, user_id: 1, favorite: true, content: "Could be a little too scary for some kids.", scare_rating: 3})
review12 = Review.create({movie_id: 12, user_id: 1, favorite: false, content: "I felt a sense of dread the entire time. It was wonderfully done.", scare_rating: 4})
review13 = Review.create({movie_id: 13, user_id: 1, favorite: true, content: "Lots of fun to watch!", scare_rating: 2})
review14 = Review.create({movie_id: 14, user_id: 1, favorite: false, content: "Love Eddie Murphy!", scare_rating: 2})
review15 = Review.create({movie_id: 15, user_id: 1, favorite: true, content: "Definitely original.", scare_rating: 4})
review16 = Review.create({movie_id: 16, user_id: 1, favorite: false, content: "Very fun.", scare_rating: 2})
review17 = Review.create({movie_id: 37, user_id: 1, favorite: true, content: "One of my all time favorites!", scare_rating: 3})

puts "done"
